### ISSUE TITLE
support for "force relaunch" 

### ISSUE THREAD

**Issue by doradsoft** [fabiospampinato/vscode-debug-launcher#2] opened 2019-04-23 08:59 UTC
First: your plugin is incredible. Thanks!
This is a feature request.
When launching an already launched debugger, the following popup appears:
![image](https://user-images.githubusercontent.com/5598420/56568067-eb74c200-65be-11e9-939a-aa70d643d026.png)
Is there an option to "force relaunch" the debugger?

**Comment by fabiospampinato** [comment] 2019-04-25 17:33
I can't reproduce this, if I run `Debug Launcher: Auto` I can restart the debugging session just by running again `Debug Launcher: Auto`, what steps are you taking to reach that error? 🤔

**Comment by fabiospampinato** [comment] 2019-08-10 21:58
Closing since no more infos have been provided.

**Closed as completed by fabiospampinato** 2019-08-10 21:58 UTC
Labels: needs more info

**Comment by doradsoft** [comment] 2020-08-19 07:04
Sorry for not supplying a reproduce.
Probably in the next release there would be a [new stopDebugging method](https://github.com/microsoft/vscode/issues/101883),
Could you please add it to `auto` behavior?
